# Docker Compose configuration

services:
  chatwise-api:
    build: .
    image: chatwise-api
    container_name: chatwise-api
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./chromadb_data:/app/chromadb_data
      - huggingface_cache:/app/.cache
    env_file:
      - .env.docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  huggingface_cache:
    # Named volume for persisting HuggingFace models between container restarts 